### ISSUE TITLE
5.2 compatibility

### ISSUE THREAD

**Issue by angelborroy-ks** [deas/contentreich-eml#7]
I've been testing this addon with 201707.

When running on a default installation, following error is logged for transformations:

```
Caused by: org.alfresco.repo.content.transform.UnsupportedTransformationException: 07280029 Transformation of (Test.eml) has not taken place because the declared mimetype (message/rfc822) does not match the detected mimetype (text/plain).
```

It looks like Alfresco included a change for 5.2 release to patch some hidden ticket **MNT-16381**: https://github.com/Alfresco/community-edition-old/commit/2faa09c32e3d543c807ebe7a768ffbd0b3338347#diff-28e111cddd9d4ddbafe4b6ad44202c65 

Exception is produced by this new `strictMimeTypeCheck` method: https://github.com/Alfresco/community-edition-old/blob/master/projects/repository/source/java/org/alfresco/repo/content/transform/AbstractContentTransformer2.java#L252

I'm bypassing this problem by setting the flag to `false` in `alfresco-global.properties`, but I don't know if by this I'm generating new problems in other features.

```
transformer.strict.mimetype.check=false
```

**Comment by hi-ko** [comment]
Hi angelborroy-ks,
instead of deactivating the mimetype check at all you could put the "wrong POI mimetype guess" pair on the whitelist in alfresco-global.properties:

        transformer.strict.mimetype.check.whitelist.mimetypes=application/eps;application/postscript;application/illustrator;application/pdf;application/x-tar;application/x-gtar;application/acp;application/zip;application/vnd.stardivision.math;application/x-tika-msoffice;message/rfc822;text/plain

So it is not an issue of the module rather an incomplete config for this new Alfresco mechanism introduced with 5.2 ;-) 

so issue could be closed?
